// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `build_base_url`, `build_request`, `get_env_api_key`, `get_provider_config`, `lang_name`, `resolve_config`, `translate_anthropic`, `translate_azure`, `translate_custom`, `translate_deepl`, `translate_google`, `translate_openai_compat`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProviderResolvedConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 初始化所有服务（翻译引擎、配置管理等）
Future<void> initServices() =>
    RustLib.instance.api.crateFfiBridgeInitServices();

/// 使用配置覆盖进行翻译。
/// 如果存在保存的提供商配置，则使用其 api_key/base_url/model。
/// 否则，回退到环境变量和默认 URL。
Future<TranslationResult> translate({
  required String text,
  required String sourceLang,
  required String targetLang,
  required String providerId,
  String? systemPromptOverride,
}) => RustLib.instance.api.crateFfiBridgeTranslate(
  text: text,
  sourceLang: sourceLang,
  targetLang: targetLang,
  providerId: providerId,
  systemPromptOverride: systemPromptOverride,
);

/// 比较多个提供商的翻译
Future<List<TranslationResult>> translateCompare({
  required String text,
  required String sourceLang,
  required String targetLang,
  required List<String> providerIds,
  String? systemPromptOverride,
}) => RustLib.instance.api.crateFfiBridgeTranslateCompare(
  text: text,
  sourceLang: sourceLang,
  targetLang: targetLang,
  providerIds: providerIds,
  systemPromptOverride: systemPromptOverride,
);

Future<String> detectLanguage({required String text}) =>
    RustLib.instance.api.crateFfiBridgeDetectLanguage(text: text);

Future<List<ProviderConfig>> getProviders() =>
    RustLib.instance.api.crateFfiBridgeGetProviders();

Future<void> saveProvider({required ProviderConfig config}) =>
    RustLib.instance.api.crateFfiBridgeSaveProvider(config: config);

Future<void> deleteProvider({required String id}) =>
    RustLib.instance.api.crateFfiBridgeDeleteProvider(id: id);

/// 测试厂商连接，返回详细信息
Future<TestResult> testProvider({required String providerId}) =>
    RustLib.instance.api.crateFfiBridgeTestProvider(providerId: providerId);

Future<ActiveSession> getActiveSession() =>
    RustLib.instance.api.crateFfiBridgeGetActiveSession();

Future<void> updateSession({
  String? providerId,
  List<String>? compareProviders,
}) => RustLib.instance.api.crateFfiBridgeUpdateSession(
  providerId: providerId,
  compareProviders: compareProviders,
);

Future<List<PromptTemplate>> getPromptTemplates() =>
    RustLib.instance.api.crateFfiBridgeGetPromptTemplates();

Future<void> savePromptTemplate({required PromptTemplate tpl}) =>
    RustLib.instance.api.crateFfiBridgeSavePromptTemplate(tpl: tpl);

Future<void> deletePromptTemplate({required String id}) =>
    RustLib.instance.api.crateFfiBridgeDeletePromptTemplate(id: id);

Future<DesktopEnv> detectDesktopEnv() =>
    RustLib.instance.api.crateFfiBridgeDetectDesktopEnv();

Future<String> ocrScreenshot() =>
    RustLib.instance.api.crateFfiBridgeOcrScreenshot();

Future<List<ShortcutBinding>> getShortcuts() =>
    RustLib.instance.api.crateFfiBridgeGetShortcuts();

Future<void> updateShortcut({required ShortcutBinding binding}) =>
    RustLib.instance.api.crateFfiBridgeUpdateShortcut(binding: binding);

Future<void> registerHotkeys({required List<ShortcutBinding> shortcuts}) =>
    RustLib.instance.api.crateFfiBridgeRegisterHotkeys(shortcuts: shortcuts);

Future<void> unregisterHotkeys() =>
    RustLib.instance.api.crateFfiBridgeUnregisterHotkeys();

/// Poll for the next hotkey event. Returns None if no event available.
Future<String?> pollHotkeyEvent() =>
    RustLib.instance.api.crateFfiBridgePollHotkeyEvent();

Future<String> getClipboardText() =>
    RustLib.instance.api.crateFfiBridgeGetClipboardText();

Future<void> setClipboardText({required String text}) =>
    RustLib.instance.api.crateFfiBridgeSetClipboardText(text: text);

Future<void> initTray() => RustLib.instance.api.crateFfiBridgeInitTray();

Future<void> showTrayNotification({
  required String title,
  required String body,
}) => RustLib.instance.api.crateFfiBridgeShowTrayNotification(
  title: title,
  body: body,
);

/// 测试厂商连接结果
class TestResult {
  final bool success;
  final String message;

  const TestResult({required this.success, required this.message});

  @override
  int get hashCode => success.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TestResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message;
}
