// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ActiveSession {
  final String lastProviderId;
  final List<String> lastCompareProviders;
  final DateTime lastUsed;

  const ActiveSession({
    required this.lastProviderId,
    required this.lastCompareProviders,
    required this.lastUsed,
  });

  @override
  int get hashCode =>
      lastProviderId.hashCode ^
      lastCompareProviders.hashCode ^
      lastUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveSession &&
          runtimeType == other.runtimeType &&
          lastProviderId == other.lastProviderId &&
          lastCompareProviders == other.lastCompareProviders &&
          lastUsed == other.lastUsed;
}

enum DesktopEnv { kdePlasma, hyprland, gnome, unknown }

class PromptTemplate {
  final String id;
  final String name;
  final String content;
  final bool isActive;
  final DateTime createdAt;

  const PromptTemplate({
    required this.id,
    required this.name,
    required this.content,
    required this.isActive,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      content.hashCode ^
      isActive.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PromptTemplate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          content == other.content &&
          isActive == other.isActive &&
          createdAt == other.createdAt;
}

class ProviderConfig {
  final String id;
  final String name;
  final String? apiKey;
  final String? apiUrl;
  final String model;
  final String authType;
  final bool isActive;
  final int sortOrder;
  final String? systemPrompt;
  final DateTime createdAt;

  const ProviderConfig({
    required this.id,
    required this.name,
    this.apiKey,
    this.apiUrl,
    required this.model,
    required this.authType,
    required this.isActive,
    required this.sortOrder,
    this.systemPrompt,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      apiKey.hashCode ^
      apiUrl.hashCode ^
      model.hashCode ^
      authType.hashCode ^
      isActive.hashCode ^
      sortOrder.hashCode ^
      systemPrompt.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          apiKey == other.apiKey &&
          apiUrl == other.apiUrl &&
          model == other.model &&
          authType == other.authType &&
          isActive == other.isActive &&
          sortOrder == other.sortOrder &&
          systemPrompt == other.systemPrompt &&
          createdAt == other.createdAt;
}

class ShortcutBinding {
  final String id;
  final String action;
  final String keyCombination;
  final bool enabled;

  const ShortcutBinding({
    required this.id,
    required this.action,
    required this.keyCombination,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      action.hashCode ^
      keyCombination.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShortcutBinding &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          keyCombination == other.keyCombination &&
          enabled == other.enabled;
}

class TranslationResult {
  final String providerId;
  final String providerName;
  final String sourceText;
  final String translatedText;
  final BigInt responseTimeMs;
  final bool isSuccess;
  final String? errorMessage;
  final BigInt promptTokens;
  final BigInt completionTokens;
  final BigInt totalTokens;

  const TranslationResult({
    required this.providerId,
    required this.providerName,
    required this.sourceText,
    required this.translatedText,
    required this.responseTimeMs,
    required this.isSuccess,
    this.errorMessage,
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      providerName.hashCode ^
      sourceText.hashCode ^
      translatedText.hashCode ^
      responseTimeMs.hashCode ^
      isSuccess.hashCode ^
      errorMessage.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationResult &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          providerName == other.providerName &&
          sourceText == other.sourceText &&
          translatedText == other.translatedText &&
          responseTimeMs == other.responseTimeMs &&
          isSuccess == other.isSuccess &&
          errorMessage == other.errorMessage &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens;
}
