// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi/bridge.dart';
import 'ffi/error.dart';
import 'ffi/types.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1189123806;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_translate_native',
        ioDirectory: '../native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateFfiBridgeDeletePromptTemplate({required String id});

  Future<void> crateFfiBridgeDeleteProvider({required String id});

  Future<DesktopEnv> crateFfiBridgeDetectDesktopEnv();

  Future<String> crateFfiBridgeDetectLanguage({required String text});

  Future<ActiveSession> crateFfiBridgeGetActiveSession();

  Future<String> crateFfiBridgeGetClipboardText();

  Future<List<PromptTemplate>> crateFfiBridgeGetPromptTemplates();

  Future<List<ProviderConfig>> crateFfiBridgeGetProviders();

  Future<List<ShortcutBinding>> crateFfiBridgeGetShortcuts();

  Future<void> crateFfiBridgeInitServices();

  Future<void> crateFfiBridgeInitTray();

  Future<String> crateFfiBridgeOcrScreenshot();

  Future<String?> crateFfiBridgePollHotkeyEvent();

  Future<void> crateFfiBridgeRegisterHotkeys({
    required List<ShortcutBinding> shortcuts,
  });

  Future<void> crateFfiBridgeSavePromptTemplate({required PromptTemplate tpl});

  Future<void> crateFfiBridgeSaveProvider({required ProviderConfig config});

  Future<void> crateFfiBridgeSetClipboardText({required String text});

  Future<void> crateFfiBridgeShowTrayNotification({
    required String title,
    required String body,
  });

  Future<TestResult> crateFfiBridgeTestProvider({required String providerId});

  Future<TranslationResult> crateFfiBridgeTranslate({
    required String text,
    required String sourceLang,
    required String targetLang,
    required String providerId,
    String? systemPromptOverride,
  });

  Future<List<TranslationResult>> crateFfiBridgeTranslateCompare({
    required String text,
    required String sourceLang,
    required String targetLang,
    required List<String> providerIds,
    String? systemPromptOverride,
  });

  Future<void> crateFfiBridgeUnregisterHotkeys();

  Future<void> crateFfiBridgeUpdateSession({
    String? providerId,
    List<String>? compareProviders,
  });

  Future<void> crateFfiBridgeUpdateShortcut({required ShortcutBinding binding});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClipboardError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClipboardError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClipboardErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ConfigError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ConfigError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ConfigErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HotkeyError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HotkeyError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_HotkeyErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OcrError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OcrError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_OcrErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TranslateError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TranslateError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TranslateErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TrayError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TrayError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TrayErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateFfiBridgeDeletePromptTemplate({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeDeletePromptTemplateConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeDeletePromptTemplateConstMeta =>
      const TaskConstMeta(
        debugName: "delete_prompt_template",
        argNames: ["id"],
      );

  @override
  Future<void> crateFfiBridgeDeleteProvider({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeDeleteProviderConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeDeleteProviderConstMeta =>
      const TaskConstMeta(debugName: "delete_provider", argNames: ["id"]);

  @override
  Future<DesktopEnv> crateFfiBridgeDetectDesktopEnv() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_desktop_env,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiBridgeDetectDesktopEnvConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeDetectDesktopEnvConstMeta =>
      const TaskConstMeta(debugName: "detect_desktop_env", argNames: []);

  @override
  Future<String> crateFfiBridgeDetectLanguage({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError,
        ),
        constMeta: kCrateFfiBridgeDetectLanguageConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeDetectLanguageConstMeta =>
      const TaskConstMeta(debugName: "detect_language", argNames: ["text"]);

  @override
  Future<ActiveSession> crateFfiBridgeGetActiveSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_active_session,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeGetActiveSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetActiveSessionConstMeta =>
      const TaskConstMeta(debugName: "get_active_session", argNames: []);

  @override
  Future<String> crateFfiBridgeGetClipboardText() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError,
        ),
        constMeta: kCrateFfiBridgeGetClipboardTextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetClipboardTextConstMeta =>
      const TaskConstMeta(debugName: "get_clipboard_text", argNames: []);

  @override
  Future<List<PromptTemplate>> crateFfiBridgeGetPromptTemplates() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prompt_template,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeGetPromptTemplatesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetPromptTemplatesConstMeta =>
      const TaskConstMeta(debugName: "get_prompt_templates", argNames: []);

  @override
  Future<List<ProviderConfig>> crateFfiBridgeGetProviders() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_provider_config,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeGetProvidersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetProvidersConstMeta =>
      const TaskConstMeta(debugName: "get_providers", argNames: []);

  @override
  Future<List<ShortcutBinding>> crateFfiBridgeGetShortcuts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_shortcut_binding,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeGetShortcutsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetShortcutsConstMeta =>
      const TaskConstMeta(debugName: "get_shortcuts", argNames: []);

  @override
  Future<void> crateFfiBridgeInitServices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiBridgeInitServicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeInitServicesConstMeta =>
      const TaskConstMeta(debugName: "init_services", argNames: []);

  @override
  Future<void> crateFfiBridgeInitTray() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError,
        ),
        constMeta: kCrateFfiBridgeInitTrayConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeInitTrayConstMeta =>
      const TaskConstMeta(debugName: "init_tray", argNames: []);

  @override
  Future<String> crateFfiBridgeOcrScreenshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError,
        ),
        constMeta: kCrateFfiBridgeOcrScreenshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeOcrScreenshotConstMeta =>
      const TaskConstMeta(debugName: "ocr_screenshot", argNames: []);

  @override
  Future<String?> crateFfiBridgePollHotkeyEvent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiBridgePollHotkeyEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgePollHotkeyEventConstMeta =>
      const TaskConstMeta(debugName: "poll_hotkey_event", argNames: []);

  @override
  Future<void> crateFfiBridgeRegisterHotkeys({
    required List<ShortcutBinding> shortcuts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_shortcut_binding(shortcuts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError,
        ),
        constMeta: kCrateFfiBridgeRegisterHotkeysConstMeta,
        argValues: [shortcuts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeRegisterHotkeysConstMeta =>
      const TaskConstMeta(
        debugName: "register_hotkeys",
        argNames: ["shortcuts"],
      );

  @override
  Future<void> crateFfiBridgeSavePromptTemplate({required PromptTemplate tpl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_prompt_template(tpl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeSavePromptTemplateConstMeta,
        argValues: [tpl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeSavePromptTemplateConstMeta =>
      const TaskConstMeta(debugName: "save_prompt_template", argNames: ["tpl"]);

  @override
  Future<void> crateFfiBridgeSaveProvider({required ProviderConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_provider_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeSaveProviderConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeSaveProviderConstMeta =>
      const TaskConstMeta(debugName: "save_provider", argNames: ["config"]);

  @override
  Future<void> crateFfiBridgeSetClipboardText({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError,
        ),
        constMeta: kCrateFfiBridgeSetClipboardTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeSetClipboardTextConstMeta =>
      const TaskConstMeta(debugName: "set_clipboard_text", argNames: ["text"]);

  @override
  Future<void> crateFfiBridgeShowTrayNotification({
    required String title,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError,
        ),
        constMeta: kCrateFfiBridgeShowTrayNotificationConstMeta,
        argValues: [title, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeShowTrayNotificationConstMeta =>
      const TaskConstMeta(
        debugName: "show_tray_notification",
        argNames: ["title", "body"],
      );

  @override
  Future<TestResult> crateFfiBridgeTestProvider({required String providerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(providerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_test_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiBridgeTestProviderConstMeta,
        argValues: [providerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeTestProviderConstMeta =>
      const TaskConstMeta(debugName: "test_provider", argNames: ["providerId"]);

  @override
  Future<TranslationResult> crateFfiBridgeTranslate({
    required String text,
    required String sourceLang,
    required String targetLang,
    required String providerId,
    String? systemPromptOverride,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(sourceLang, serializer);
          sse_encode_String(targetLang, serializer);
          sse_encode_String(providerId, serializer);
          sse_encode_opt_String(systemPromptOverride, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_translation_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError,
        ),
        constMeta: kCrateFfiBridgeTranslateConstMeta,
        argValues: [
          text,
          sourceLang,
          targetLang,
          providerId,
          systemPromptOverride,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeTranslateConstMeta => const TaskConstMeta(
    debugName: "translate",
    argNames: [
      "text",
      "sourceLang",
      "targetLang",
      "providerId",
      "systemPromptOverride",
    ],
  );

  @override
  Future<List<TranslationResult>> crateFfiBridgeTranslateCompare({
    required String text,
    required String sourceLang,
    required String targetLang,
    required List<String> providerIds,
    String? systemPromptOverride,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(sourceLang, serializer);
          sse_encode_String(targetLang, serializer);
          sse_encode_list_String(providerIds, serializer);
          sse_encode_opt_String(systemPromptOverride, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_translation_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError,
        ),
        constMeta: kCrateFfiBridgeTranslateCompareConstMeta,
        argValues: [
          text,
          sourceLang,
          targetLang,
          providerIds,
          systemPromptOverride,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeTranslateCompareConstMeta =>
      const TaskConstMeta(
        debugName: "translate_compare",
        argNames: [
          "text",
          "sourceLang",
          "targetLang",
          "providerIds",
          "systemPromptOverride",
        ],
      );

  @override
  Future<void> crateFfiBridgeUnregisterHotkeys() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError,
        ),
        constMeta: kCrateFfiBridgeUnregisterHotkeysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeUnregisterHotkeysConstMeta =>
      const TaskConstMeta(debugName: "unregister_hotkeys", argNames: []);

  @override
  Future<void> crateFfiBridgeUpdateSession({
    String? providerId,
    List<String>? compareProviders,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(providerId, serializer);
          sse_encode_opt_list_String(compareProviders, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeUpdateSessionConstMeta,
        argValues: [providerId, compareProviders],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeUpdateSessionConstMeta =>
      const TaskConstMeta(
        debugName: "update_session",
        argNames: ["providerId", "compareProviders"],
      );

  @override
  Future<void> crateFfiBridgeUpdateShortcut({
    required ShortcutBinding binding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_shortcut_binding(binding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError,
        ),
        constMeta: kCrateFfiBridgeUpdateShortcutConstMeta,
        argValues: [binding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeUpdateShortcutConstMeta =>
      const TaskConstMeta(debugName: "update_shortcut", argNames: ["binding"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClipboardError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClipboardError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ConfigError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ConfigError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HotkeyError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HotkeyError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OcrError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OcrError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TranslateError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TranslateError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TrayError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TrayError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError;

  @protected
  ClipboardError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClipboardErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ConfigError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConfigErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HotkeyError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HotkeyErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OcrError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OcrErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TranslateError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TranslateErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TrayError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrayErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  ClipboardError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClipboardErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ConfigError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConfigErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HotkeyError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HotkeyErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OcrError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OcrErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TranslateError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TranslateErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TrayError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrayErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActiveSession dco_decode_active_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ActiveSession(
      lastProviderId: dco_decode_String(arr[0]),
      lastCompareProviders: dco_decode_list_String(arr[1]),
      lastUsed: dco_decode_Chrono_Utc(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PromptTemplate dco_decode_box_autoadd_prompt_template(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_prompt_template(raw);
  }

  @protected
  ProviderConfig dco_decode_box_autoadd_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_provider_config(raw);
  }

  @protected
  ShortcutBinding dco_decode_box_autoadd_shortcut_binding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shortcut_binding(raw);
  }

  @protected
  DesktopEnv dco_decode_desktop_env(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DesktopEnv.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<PromptTemplate> dco_decode_list_prompt_template(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_prompt_template).toList();
  }

  @protected
  List<ProviderConfig> dco_decode_list_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_provider_config).toList();
  }

  @protected
  List<ShortcutBinding> dco_decode_list_shortcut_binding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_shortcut_binding).toList();
  }

  @protected
  List<TranslationResult> dco_decode_list_translation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_translation_result).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  PromptTemplate dco_decode_prompt_template(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PromptTemplate(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      isActive: dco_decode_bool(arr[3]),
      createdAt: dco_decode_Chrono_Utc(arr[4]),
    );
  }

  @protected
  ProviderConfig dco_decode_provider_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ProviderConfig(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      apiKey: dco_decode_opt_String(arr[2]),
      apiUrl: dco_decode_opt_String(arr[3]),
      model: dco_decode_String(arr[4]),
      authType: dco_decode_String(arr[5]),
      isActive: dco_decode_bool(arr[6]),
      sortOrder: dco_decode_i_32(arr[7]),
      systemPrompt: dco_decode_opt_String(arr[8]),
      createdAt: dco_decode_Chrono_Utc(arr[9]),
    );
  }

  @protected
  ShortcutBinding dco_decode_shortcut_binding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ShortcutBinding(
      id: dco_decode_String(arr[0]),
      action: dco_decode_String(arr[1]),
      keyCombination: dco_decode_String(arr[2]),
      enabled: dco_decode_bool(arr[3]),
    );
  }

  @protected
  TestResult dco_decode_test_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TestResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  TranslationResult dco_decode_translation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TranslationResult(
      providerId: dco_decode_String(arr[0]),
      providerName: dco_decode_String(arr[1]),
      sourceText: dco_decode_String(arr[2]),
      translatedText: dco_decode_String(arr[3]),
      responseTimeMs: dco_decode_u_64(arr[4]),
      isSuccess: dco_decode_bool(arr[5]),
      errorMessage: dco_decode_opt_String(arr[6]),
      promptTokens: dco_decode_u_64(arr[7]),
      completionTokens: dco_decode_u_64(arr[8]),
      totalTokens: dco_decode_u_64(arr[9]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ClipboardError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClipboardErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ConfigError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ConfigErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HotkeyError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HotkeyErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OcrError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OcrErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TranslateError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TranslateErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TrayError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TrayErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  ClipboardError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClipboardErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ConfigError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ConfigErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HotkeyError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HotkeyErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OcrError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OcrErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TranslateError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TranslateErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TrayError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TrayErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActiveSession sse_decode_active_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lastProviderId = sse_decode_String(deserializer);
    var var_lastCompareProviders = sse_decode_list_String(deserializer);
    var var_lastUsed = sse_decode_Chrono_Utc(deserializer);
    return ActiveSession(
      lastProviderId: var_lastProviderId,
      lastCompareProviders: var_lastCompareProviders,
      lastUsed: var_lastUsed,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PromptTemplate sse_decode_box_autoadd_prompt_template(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_prompt_template(deserializer));
  }

  @protected
  ProviderConfig sse_decode_box_autoadd_provider_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_provider_config(deserializer));
  }

  @protected
  ShortcutBinding sse_decode_box_autoadd_shortcut_binding(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_shortcut_binding(deserializer));
  }

  @protected
  DesktopEnv sse_decode_desktop_env(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DesktopEnv.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<PromptTemplate> sse_decode_list_prompt_template(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PromptTemplate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_prompt_template(deserializer));
    }
    return ans_;
  }

  @protected
  List<ProviderConfig> sse_decode_list_provider_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_config(deserializer));
    }
    return ans_;
  }

  @protected
  List<ShortcutBinding> sse_decode_list_shortcut_binding(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ShortcutBinding>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_shortcut_binding(deserializer));
    }
    return ans_;
  }

  @protected
  List<TranslationResult> sse_decode_list_translation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranslationResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_translation_result(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PromptTemplate sse_decode_prompt_template(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return PromptTemplate(
      id: var_id,
      name: var_name,
      content: var_content,
      isActive: var_isActive,
      createdAt: var_createdAt,
    );
  }

  @protected
  ProviderConfig sse_decode_provider_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_apiKey = sse_decode_opt_String(deserializer);
    var var_apiUrl = sse_decode_opt_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_authType = sse_decode_String(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_sortOrder = sse_decode_i_32(deserializer);
    var var_systemPrompt = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return ProviderConfig(
      id: var_id,
      name: var_name,
      apiKey: var_apiKey,
      apiUrl: var_apiUrl,
      model: var_model,
      authType: var_authType,
      isActive: var_isActive,
      sortOrder: var_sortOrder,
      systemPrompt: var_systemPrompt,
      createdAt: var_createdAt,
    );
  }

  @protected
  ShortcutBinding sse_decode_shortcut_binding(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_action = sse_decode_String(deserializer);
    var var_keyCombination = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return ShortcutBinding(
      id: var_id,
      action: var_action,
      keyCombination: var_keyCombination,
      enabled: var_enabled,
    );
  }

  @protected
  TestResult sse_decode_test_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return TestResult(success: var_success, message: var_message);
  }

  @protected
  TranslationResult sse_decode_translation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerId = sse_decode_String(deserializer);
    var var_providerName = sse_decode_String(deserializer);
    var var_sourceText = sse_decode_String(deserializer);
    var var_translatedText = sse_decode_String(deserializer);
    var var_responseTimeMs = sse_decode_u_64(deserializer);
    var var_isSuccess = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    var var_promptTokens = sse_decode_u_64(deserializer);
    var var_completionTokens = sse_decode_u_64(deserializer);
    var var_totalTokens = sse_decode_u_64(deserializer);
    return TranslationResult(
      providerId: var_providerId,
      providerName: var_providerName,
      sourceText: var_sourceText,
      translatedText: var_translatedText,
      responseTimeMs: var_responseTimeMs,
      isSuccess: var_isSuccess,
      errorMessage: var_errorMessage,
      promptTokens: var_promptTokens,
      completionTokens: var_completionTokens,
      totalTokens: var_totalTokens,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError(
    ClipboardError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClipboardErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError(
    ConfigError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ConfigErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError(
    HotkeyError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HotkeyErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError(
    OcrError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OcrErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError(
    TranslateError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TranslateErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError(
    TrayError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TrayErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClipboardError(
    ClipboardError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClipboardErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConfigError(
    ConfigError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ConfigErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHotkeyError(
    HotkeyError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HotkeyErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOcrError(
    OcrError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OcrErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTranslateError(
    TranslateError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TranslateErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrayError(
    TrayError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TrayErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_active_session(ActiveSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lastProviderId, serializer);
    sse_encode_list_String(self.lastCompareProviders, serializer);
    sse_encode_Chrono_Utc(self.lastUsed, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_prompt_template(
    PromptTemplate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_prompt_template(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_provider_config(
    ProviderConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_provider_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_shortcut_binding(
    ShortcutBinding self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shortcut_binding(self, serializer);
  }

  @protected
  void sse_encode_desktop_env(DesktopEnv self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prompt_template(
    List<PromptTemplate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_prompt_template(item, serializer);
    }
  }

  @protected
  void sse_encode_list_provider_config(
    List<ProviderConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_config(item, serializer);
    }
  }

  @protected
  void sse_encode_list_shortcut_binding(
    List<ShortcutBinding> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_shortcut_binding(item, serializer);
    }
  }

  @protected
  void sse_encode_list_translation_result(
    List<TranslationResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_translation_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_prompt_template(
    PromptTemplate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_provider_config(
    ProviderConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.apiKey, serializer);
    sse_encode_opt_String(self.apiUrl, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.authType, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_i_32(self.sortOrder, serializer);
    sse_encode_opt_String(self.systemPrompt, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_shortcut_binding(
    ShortcutBinding self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.action, serializer);
    sse_encode_String(self.keyCombination, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_test_result(TestResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_translation_result(
    TranslationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerId, serializer);
    sse_encode_String(self.providerName, serializer);
    sse_encode_String(self.sourceText, serializer);
    sse_encode_String(self.translatedText, serializer);
    sse_encode_u_64(self.responseTimeMs, serializer);
    sse_encode_bool(self.isSuccess, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
    sse_encode_u_64(self.promptTokens, serializer);
    sse_encode_u_64(self.completionTokens, serializer);
    sse_encode_u_64(self.totalTokens, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ClipboardErrorImpl extends RustOpaque implements ClipboardError {
  // Not to be used by end users
  ClipboardErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClipboardErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ClipboardError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClipboardError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClipboardErrorPtr,
  );
}

@sealed
class ConfigErrorImpl extends RustOpaque implements ConfigError {
  // Not to be used by end users
  ConfigErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ConfigErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ConfigError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ConfigError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ConfigErrorPtr,
  );
}

@sealed
class HotkeyErrorImpl extends RustOpaque implements HotkeyError {
  // Not to be used by end users
  HotkeyErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HotkeyErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HotkeyError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HotkeyError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HotkeyErrorPtr,
  );
}

@sealed
class OcrErrorImpl extends RustOpaque implements OcrError {
  // Not to be used by end users
  OcrErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OcrErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_OcrError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_OcrError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_OcrErrorPtr,
  );
}

@sealed
class TranslateErrorImpl extends RustOpaque implements TranslateError {
  // Not to be used by end users
  TranslateErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TranslateErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TranslateError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TranslateError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TranslateErrorPtr,
  );
}

@sealed
class TrayErrorImpl extends RustOpaque implements TrayError {
  // Not to be used by end users
  TrayErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TrayErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TrayError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TrayError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TrayErrorPtr,
  );
}
