# Hyprland 配置文件 - xym_ft
# 适用于 Hyprland 0.54+
# 添加到 ~/.config/hypr/hyprland.conf 或 include

windowrule {
    name = xym-ft-float
    match:class = ^(com.xym.ft)$
    float = true
    size = 400 600
    center = true
    pin = true
    animation = popin 80%
    
}